### PR TITLE
Updated Kel'Thuzad script

### PR DESCRIPTION
**Pull request by namreeb**
Adjust KT script with new Elysium timers

### CODE REVIEW

**Comment by Hosq** [comment]
Not sure where you got your timers but from what i can see only ones that need changing are 
frostboltVolley which should be 15-17 instead of 15-30 you have it set to static 15
mindcontrol should be 60-75 instead of 60-90 and you have it at 72-86
firstGuardians should be 8 instead of 5 and you have it at 10
all other timers seem to be correct already.
also cant figure out why you went and renamed/deleted some of them

**Comment by namreeb** [comment]
I renamed the variables that were ambiguously named.  These changes reflect changes to Kel'Thuzad that are going live on Elysium in a few minutes.

**Comment by Hosq** [comment]
can you link me where you got these so i can check them

**Comment by namreeb** [comment]
The Elysium core is no longer open source.  But I am the one who made the changes.  We are doing a raid to test it shortly.  If there are any changes I will try to make them and amend this pull request.

**Comment by Hosq** [comment]
Oh right you were talking about elysium got my servers mixed up. Id suggest you just fork this and do all the changes you want since doing these changes would brake it on lightshope

**Pull request closed without merging**
