### PR TITLE
[WIP] Add IntervalBar to API

### PR DESCRIPTION
**Pull request by birdayz**
This PR adds IntervalBar to the API, which lets you define Bars specifically designed for random intervals, which is common for many boss abilities on Elysium.

IntervalBar works like Bar, but gets two timers instead of one. The first timer indicates the earliest occurrence of the event, the second one represents the latest occurrence. The timers works as usual, with one difference: when the first timer is reached (earliest occurrence), the timer stays at zero and does not disappear. Then, the bar fades progressively for the remaining time until the latest occurrence is reached. This should give users a clear indication if an event, represented by the bar, already happened.

Additionally, the API function adds an abstraction to these random timers. If we want to change for example the layout of the bar for random timers, we can just do it without further adjusting bosses. Just change the implementation of IntervalBar in Core.lua. 
This means, we should adjust random boss timers to use IntervalBar where it makes sense.

I included the changes to Magmadar's Panic to show how it looks like. If this PR gets approved, i am willing to adjust other bosses as well.

I made a youtube video to show how this looks like:
https://www.youtube.com/watch?v=5AiyANd6fJI&feature=youtu.be

The timer is 30s - 35s. It runs from 30 to 0s, then it fades for five seconds (which should be the latest point in time when the actual fear should occour).

### CODE REVIEW

**Comment by birdayz** [comment]
Another point for discussion: Should all random timers be called 'Possible XYZ' instead of 'XYZ' ?
IMO it totally makes sense to use the 'possible' terminology every time the event is random +/- some seconds, so the users gets this information.

**Comment by birdayz** [comment]
Sidenote: This can avoid confusion like with https://github.com/Hosq/BigWigs/issues/5

**Comment by strudelkuchen** [comment]
Seems like a good idea. 

> Should all random timers be called 'Possible XYZ' instead of 'XYZ' 

Also a good idea.

**Comment by birdayz** [comment]
TODO: Add an option to enable or disable the bar fading (ON by default)

**Pull request merged**
